USE Northwind

-- 1
SELECT FIRSTNAME AS NOMBRE, LASTNAME AS APELLIDO
FROM EMPLOYEES

-- 2
SELECT *
FROM EMPLOYEES
WHERE DATEDIFF(YEAR, BIRTHDATE, HIREDATE) BETWEEN 30 AND 50

-- 3
SELECT 
    UPPER(CONCAT(
        FirstName, ' ', LastName, 
        ' ENTRÓ A TRABAJAR UN ',
        DATENAME(dw, HireDate), ' ', 
        FORMAT(HireDate, 'dd "DE" MMMM "DE" yyyy'), 
        ' CON UNA EDAD DE ', 
        DATEDIFF(YEAR, BirthDate, HireDate), ' AÑOS'
    )) AS InformacionEmpleado
FROM Employees;

-- 4
SELECT ORDERID, ORDERDATE
FROM ORDERS
WHERE 
    DATEPART(DW, ORDERDATE) = 2 AND
    DATEPART(MM, ORDERDATE) BETWEEN 1 AND 6
ORDER BY ORDERID

-- 5
SELECT O.ORDERID, O.ORDERDATE
FROM ORDERS O
INNER JOIN EMPLOYEES E ON O.EMPLOYEEID = E.EMPLOYEEID
WHERE
    DATEPART(DW, O.ORDERDATE) = 6 AND
    E.EMPLOYEEID IN (1, 3, 5)
ORDER BY O.OrderID

-- 6
SELECT
    CONCAT(
        'la orden ', O.ORDERID, ' ',
        'fue realizada por el cliente ', UPPER(C.CONTACTNAME), ' ',
        'y atendida por el empleado ', E.EMPLOYEEID
    ) AS InformacionOrden
FROM ORDERS O
INNER JOIN EMPLOYEES E ON O.EMPLOYEEID = E.EMPLOYEEID
INNER JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID

-- 7
SELECT CUSTOMERID, CONTACTNAME
FROM CUSTOMERS 
WHERE CONTACTNAME LIKE '[^aeiou]%' AND LEN(CONTACTNAME) > 10

-- 8
SELECT *
FROM PRODUCTS
WHERE PRODUCTNAME LIKE '[ABN]%N'

-- 9
SELECT FIRSTNAME, LASTNAME
FROM EMPLOYEES
WHERE FIRSTNAME LIKE '%[^AEIOU]' AND LASTNAME LIKE '%[^AEIOU]'

-- 10
SELECT *
FROM ORDERS
WHERE 
    DATENAME(MM, ORDERDATE) LIKE '[aeiou]%'

-- 11
SELECT PRODUCTID, PRODUCTNAME
FROM PRODUCTS
WHERE PRODUCTNAME LIKE '%[AEIOU]%[AEIOU]%[AEIOU]%' AND PRODUCTNAME NOT LIKE '%[AEIOU]%[AEIOU]%[AEIOU]%[AEIOU]%'

-- 12
SELECT *
FROM ORDERS
WHERE DATEPART(YY, ORDERDATE) % 3 = 0

-- 13
SELECT *
FROM ORDERS O
WHERE 
    (
        DATEPART(DW, O.ORDERDATE) = 1 OR -- DOMINGO
        DATEPART(DW, O.ORDERDATE) = 7 -- SABADO
    ) AND
    EMPLOYEEID IN (1,2,5)

-- 14
SELECT *
FROM ORDERS
WHERE SHIPVIA IS NULL OR DATEPART(MM, ORDERDATE) = 1

-- 15
SELECT TOP 10 *
FROM ORDERS
WHERE
    DATEPART(YY, ORDERDATE) = 1997
ORDER BY ORDERDATE DESC

-- 16
SELECT TOP 10 *
FROM PRODUCTS
WHERE SUPPLIERID IN (1, 2, 5)
ORDER BY UNITPRICE DESC

-- 17
SELECT TOP 4 *
FROM EMPLOYEES
ORDER BY HIREDATE ASC

-- 18
SELECT *
FROM EMPLOYEES
WHERE
    (
        DATEDIFF(YEAR, BIRTHDATE, HIREDATE) IN (10, 20, 30) AND
        DATEDIFF(YEAR, BIRTHDATE, GETDATE()) > 30
    ) OR (
        ADDRESS IS NOT NULL AND REGION IS NULL
    )

-- 19
SELECT *
FROM ORDERS
WHERE SHIPPOSTALCODE NOT LIKE '%[^a-zA-Z]%'

-- 20
SELECT *
FROM ORDERS
WHERE
    DATEPART(YEAR, ORDERDATE) = 1996 AND
    DATENAME(MONTH, ORDERDATE) LIKE '%R%'