USE FERRETERIAS
GO

-- VIEW 1
CREATE VIEW VW_ARTICULOS AS
SELECT
	-- ARTICULOS
	A.ARTID, A.ARTNOMBRE, A.ARTDESCRIPCION, A.ARTPRECIO,
	-- FAMILIAS
	F.FAMID, F.FAMNOMBRE, F.FAMDESCRIPCION
FROM ARTICULOS A
INNER JOIN FAMILIAS F ON A.FAMID = F.FAMID
GO

-- VIEW 2
CREATE VIEW VW_CLIENTES AS
SELECT
	-- CLIENTES
	C.CTEID, C.CTENOMBRE, C.CTEAPEPAT, C.CTEAPEMAT, C.CTEDOM, C.CTETEL, C.CTECEL, C.CTERFC, C.CTECURP, C.CTEFECHANACIMIENTO, C.CTESEXO,
	-- COLONIAS
	CO.COLID, CO.COLNOMBRE, CO.COLCP,
	-- MUNICIPIOS
	M.MUNID, M.MUNNOMBRE
FROM CLIENTES C
INNER JOIN COLONIAS CO ON C.COLID = CO.COLID
INNER JOIN MUNICIPIOS M ON CO.MUNID = M.MUNID
GO

-- VIEW 3
CREATE VIEW VW_EMPLEADOS AS
SELECT E.EMPID, E.EMPNOMBRE, E.EMPAPEPAT, E.EMPAPEMAT, E.EMPDOM, E.EMPTEL, E.EMPCEL, E.EMPFECHAINGRESO, E.EMPFECHANACIMIENTO,
Z.ZONAID, Z.ZONANOMBRE
FROM EMPLEADOS E
INNER JOIN ZONAS Z ON E.ZONAID = Z.ZONAID;
GO

--VIEW 4
CREATE VIEW VW_VENTAS AS
SELECT 
	V.VTEFOLIO, V.VTEFECHA,
	F.FERRID, F.FERRNOMBRE, F.FERRDOMICILIO, F.FERRTEL,
	VE.*,
	C.*
FROM VENTAS V
INNER JOIN FERRETERIA F ON V.FERRID = F.FERRID
INNER JOIN VW_EMPLEADOS VE ON V.EMPID = VE.EMPID
INNER JOIN VW_CLIENTES C ON V.CTEID = C.CTEID
GO

-- VIEW 5
CREATE VIEW VW_DETALLES AS
SELECT
	-- VIEW 1
	A.*,
	-- VIEW 4
	V.*
FROM DETALLES D
INNER JOIN VW_ARTICULOS A ON A.ARTID = D.ARTID -- VIEW 1 A VIEW 5
INNER JOIN VW_VENTAS V ON V.VTEFOLIO = D.VTEFOLIO -- VIEW 4 A VIEW 5
GO




-- SELECTS
SELECT * FROM VW_ARTICULOS
SELECT * FROM VW_CLIENTES
SELECT * FROM VW_EMPLEADOS
SELECT * FROM VW_VENTAS
SELECT * FROM VW_DETALLES

-- DROPS
DROP VIEW VW_ARTICULOS
DROP VIEW VW_CLIENTES
DROP VIEW VW_EMPLEADOS
DROP VIEW VW_VENTAS
DROP VIEW VW_DETALLES
